### ISSUE TITLE
Get ESDoc generation working again

### ISSUE THREAD

**Issue by christineyen** [honeycombio/libhoney-js#31]
Trying to run `esdoc` (version `1.1.0`) spits back:
```
parse: /Users/cyen/src/honeycomb/libhoney-js/src/.external-ecmascript.js
parse: /Users/cyen/src/honeycomb/libhoney-js/src/__tests__/builder_test.js
parse: /Users/cyen/src/honeycomb/libhoney-js/src/__tests__/event_test.js
parse: /Users/cyen/src/honeycomb/libhoney-js/src/__tests__/libhoney_test.js
parse: /Users/cyen/src/honeycomb/libhoney-js/src/__tests__/transmission_test.js
parse: /Users/cyen/src/honeycomb/libhoney-js/src/builder.js
parse: /Users/cyen/src/honeycomb/libhoney-js/src/event.js
parse: /Users/cyen/src/honeycomb/libhoney-js/src/foreach.js
parse: /Users/cyen/src/honeycomb/libhoney-js/src/libhoney.js
parse: /Users/cyen/src/honeycomb/libhoney-js/src/transmission.js
/Users/cyen/src/honeycomb/libhoney-js/node_modules/esdoc-type-inference-plugin/src/Plugin.js:269
    const body = node.body;
                      ^

TypeError: Cannot read property 'body' of undefined
    at Plugin._inferenceReturn (/Users/cyen/src/honeycomb/libhoney-js/node_modules/esdoc-type-inference-plugin/src/Plugin.js:269:23)
    at Plugin._inferenceMethod (/Users/cyen/src/honeycomb/libhoney-js/node_modules/esdoc-type-inference-plugin/src/Plugin.js:31:42)
    at Plugin._exec (/Users/cyen/src/honeycomb/libhoney-js/node_modules/esdoc-type-inference-plugin/src/Plugin.js:17:10)
    at Plugin.onHandleDocs (/Users/cyen/src/honeycomb/libhoney-js/node_modules/esdoc-type-inference-plugin/src/Plugin.js:11:10)
    at Plugin._execHandler (/Users/cyen/.nvm/versions/node/v9.9.0/lib/node_modules/esdoc/out/src/Plugin/Plugin.js:55:26)
    at Plugin.onHandleDocs (/Users/cyen/.nvm/versions/node/v9.9.0/lib/node_modules/esdoc/out/src/Plugin/Plugin.js:135:10)
    at Function.generate (/Users/cyen/.nvm/versions/node/v9.9.0/lib/node_modules/esdoc/out/src/ESDoc.js:132:32)
    at ESDocCLI.exec (/Users/cyen/.nvm/versions/node/v9.9.0/lib/node_modules/esdoc/out/src/ESDocCLI.js:71:23)
    at Object.<anonymous> (/Users/cyen/.nvm/versions/node/v9.9.0/lib/node_modules/esdoc/out/src/ESDocCLI.js:182:7)
    at Module._compile (module.js:649:30)
```

**Comment by christineyen** [comment]
... well esdoc.org started working again and everything seems fine, so ¯\_(ツ)_/¯
