### ISSUE TITLE
Hexoid/Formidable/Superagent dependencies causing errors with Next 14+

### ISSUE THREAD

**Issue by ztratar** [honeycombio/libhoney-js#432]
```
TypeError: hexoid is not a function
    at __webpack_require__ (/Users/ztratar/playground/embra/packages/app/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/ztratar/playground/embra/packages/app/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/ztratar/playground/embra/packages/app/.next/server/webpack-runtime.js:33:43)
    at eval (./services/honey.ts:5:66)
    at (ssr)/./services/honey.ts (/Users/ztratar/playground/embra/packages/app/.next/server/app/chat/page.js:3220:1)
    at __webpack_require__ (/Users/ztratar/playground/embra/packages/app/.next/server/webpack-runtime.js:33:43)
    at eval (./services/auth.ts:7:72)
    at (ssr)/./services/auth.ts (/Users/ztratar/playground/embra/packages/app/.next/server/app/chat/page.js:3165:1)
    at __webpack_require__ (/Users/ztratar/playground/embra/packages/app/.next/server/webpack-runtime.js:33:43)
    at eval (./lib/app.ts:11:71)
    at (ssr)/./lib/app.ts (/Users/ztratar/playground/embra/packages/app/.next/server/app/chat/page.js:2813:1)
    at __webpack_require__ (/Users/ztratar/playground/embra/packages/app/.next/server/webpack-runtime.js:33:43)
    at eval (./lib/useContainerDimensions.ts:5:65)
    at (ssr)/./lib/useContainerDimensions.ts (/Users/ztratar/playground/embra/packages/app/.next/server/app/chat/page.js:2967:1)
    at __webpack_require__ (/Users/ztratar/playground/embra/packages/app/.next/server/webpack-runtime.js:33:43)
    at eval (./components/chat/Chat.tsx:15:84)
    at (ssr)/./components/chat/Chat.tsx (/Users/ztratar/playground/embra/packages/app/.next/server/app/chat/page.js:701:1)
    at __webpack_require__ (/Users/ztratar/playground/embra/packages/app/.next/server/webpack-runtime.js:33:43)
    at eval (./app/chat/page.tsx:10:78)
    at (ssr)/./app/chat/page.tsx (/Users/ztratar/playground/embra/packages/app/.next/server/app/chat/page.js:484:1)
    at Object.__webpack_require__ [as require] (/Users/ztratar/playground/embra/packages/app/.next/server/webpack-runtime.js:33:43)
digest: "3267445951"
```

**Versions**

- Node: 20
- Libhoney: 4.3.0

**Steps to reproduce**

1. Install an app using Next 14 boilerplate.
2. Try to use the honey library anywhere
3. On page load, SSR will attempt to attempt to force webpack to compile, which errors.

This is an exports problem. Hexoid knows about it and has patched it in 2.0.0, but formidible still points to 1.0.0

https://github.com/lukeed/hexoid/issues/7

And all these problems for something akin to fetch?

**Additional context**

**Comment by codeboten** [comment]
Thanks for reporting @ztratar, will take a look at bumping the superagent dependency

**Comment by kentquirk** [comment]
Bumping the Formidible dependency will likely work, as they've now updated to the newer hexoid.

**Comment by lachlanjc** [comment]
Could we use native Node/JS `fetch` instead of superagent now? Is the dependency still necessary?
